# Generated by Django 2.2.2 on 2019-10-15 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentcomponents', '0012_assessment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdocument',
            old_name='gaurdian_picture',
            new_name='guardian_picture',
        ),
        migrations.CreateModel(
            name='AssessmentAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('field', models.CharField(blank=True, max_length=200, null=True)),
                ('admission_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentcomponents.StudentDetail')),
                ('lookup_assessment_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentcomponents.LookUp')),
            ],
        ),
    ]
