# Generated by Django 2.2.2 on 2019-11-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentcomponents', '0013_auto_20191015_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='disability',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='lookup_inputvalue',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='lookup_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='lookup_outputvalue',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='class1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='class_teacher',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='disability',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='identification_mark',
            field=models.CharField(max_length=500, null=True, verbose_name='Identification Marks'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='last_attended_institute_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Last attended Institute Name'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='reason_for_leaving',
            field=models.CharField(max_length=500, null=True, verbose_name='Reason for leaving'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='referred_by',
            field=models.CharField(max_length=200, null=True, verbose_name='Referred By'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='religion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentparent',
            name='email_id',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Id'),
        ),
        migrations.AlterField(
            model_name='studentparent',
            name='occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentparent',
            name='parent_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentsibling',
            name='sibling_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentsibling',
            name='sibling_occupation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
