# Generated by Django 2.2.2 on 2020-02-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentcomponents', '0014_auto_20191101_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpaidrecord',
            name='fees_comments',
            field=models.CharField(blank=True, default='No Comments Added (max 400)', max_length=400, null=True, verbose_name='Comments'),
        ),
    ]
